<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td>
                <h3 class="icon-head head-blog">
                    <?php echo Mage::helper('stuntcoders_googleshopping')->__('Google Shopping Feeds'); ?>
                </h3>
            </td>
            <td class="a-right">
                <?php echo $this->getChildHtml('googleshopping.addnew'); ?>
            </td>
        </tr>
    </table>
</div>
<?php echo $this->getLayout()->createBlock('stuntcoders_googleshopping/index_grid')->toHtml(); ?>