<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td>
                <h3 class="icon-head head-blog">
                    <?php echo Mage::helper('stuntcoders_googleshopping')->__('Manage Google Shopping Feed'); ?>
                </h3>
            </td>
            <td class="a-right">
                <?php echo $this->getChildHtml('googleshopping.delete'); ?>
                <?php echo $this->getChildHtml('googleshopping.savenew'); ?>
                <?php echo $this->getChildHtml('googleshopping.generate'); ?>
            </td>
        </tr>
    </table>
</div>
<?php echo $this->getLayout()->createBlock('stuntcoders_googleshopping/add_form')->toHtml(); ?>
